### ISSUE TITLE
Extend the delay node

### ISSUE THREAD

**Issue by hardillb** [eisbehr-/node-red-throttle#1]
The built in delay node already does rate limiting, why create a new node rather than submit a pull request that extends the existing node?

The project is now hosted by the Javascript foundation and has a new somewhat lighter weight process to submit a CLA

**Comment by eisbehr-** [comment]
Hello @hardillb,

I will not raise a CLA on any time. I've done a PR before on Node-RED and learned that it would be rejected then. So there will be no other improvemnts from me on the core. 

Thank you.
