### ISSUE TITLE
timeLimitType milliseconds

### ISSUE THREAD

**Issue by hobbyquaker** [eisbehr-/node-red-throttle#2]
I'd like to use time limit <1s, would be useful for me with e.g. sliders in node-red-dashboard that control brightness of hue lamps, 1s is a bit too long for this usecase, i'd like to send messages every 200ms. If you would appreciate this feature and don't wanna do it yourself I can send you a Pullrequest.

**Comment by hobbyquaker** [comment]
ah - oh - just realized that this can already be done with the built-in delay node, so I close this issue :)

**Comment by eisbehr-** [comment]
Hello @hobbyquaker,

glad you found a solution for yours. But this would be a nice addition anyway. So I will implement this, could be usefull for others too.

**Comment by eisbehr-** [comment]
Added with feature with version 0.1.3.
