### ISSUE TITLE
'Usage' of new feature missing in documentation

### ISSUE THREAD

**Issue by bartbutenaers** [eisbehr-/node-red-throttle#4]
Hey @eisbehr- ,

Thanks for releasing version 0.1.4 !

Seems to be working fine.  The only thing that needs to be done is updating the 'Usage' area, to add a section about the new 'block size' feature:

![image](https://cloud.githubusercontent.com/assets/14224149/21963545/1c061748-db3d-11e6-8fee-078178be4e3b.png)

Kind regards,
Bart Butenaers

**Comment by eisbehr-** [comment]
Yes, correct. Will update it ...
