### ISSUE TITLE
Throttle using most recent message

### ISSUE THREAD

**Issue by asterix555** [eisbehr-/node-red-throttle#6]
Hi,
I'd like to use node-red-throttle to combine several dimmers with feedback. For this I need a throttle node, but in "reverse" logic. So the first message is getting delayed by n-seconds. If, in meantime, another message is received, ignore the first package, delay the second one by n-seconds and so on...

Is that somehow possible with this plugin?

kind regards

**Comment by eisbehr-** [comment]
Hello @asterix555 
This is not possible with this node. But honestly, I would use a function node to build something like that. It's pretty easy to do. Use `setTimeout` and `clearTimeout` and it's mostly done. ;)

**Comment by asterix555** [comment]
Hi Eisbehr,

thank you for your fast response. I'll need to take a closer look how to write functions,..

However I found a function that does exactly what I need: A trigger, that sends only on the falling edge and gets extended by any input:

![2017-11-21 09_21_38-node-red _ 192 168 8 151](https://user-images.githubusercontent.com/4613604/33061739-7241c1bc-ce9d-11e7-9855-5db5e064a641.png)
